language: python

branches:
  only:
    - master

python:
  - "2.7"
  - "3.4"
  - "3.5"

# command to install dependencies
install:
    - pip install -r requirements.txt
    - pip freeze
    - pip install coveralls

services:
    - mysql

before_install:
    - sudo apt-get install python-dev python3-dev

before_script:
  - mysql -u root -e 'create database lychee_ci DEFAULT CHARACTER SET utf8 DEFAULT COLLATE utf8_general_ci;'
  - mysql -u root  -e "create user 'lychee_ci'@'localhost' IDENTIFIED BY 'lychee_ci';"
  - mysql -u root -e "GRANT ALL ON lychee_ci.* TO 'lychee_ci'@'localhost';"

# command to run tests
script:
    coverage run -m --source ./lycheesync py.test -c ./ressources/pytest.ini  --showlocals  --duration=3 -v  -s --confpath=${PWD}/ressources/test_conf.json

after_sucess:
  - ls
  - COVERALLS_REPO_TOKEN=cktxxxo0o6vRPJR3aflmfm4Oal2B32qRl coveralls
